environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
    MSYS2: 1
  - TARGET: x86_64-pc-windows-msvc
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    BITS: 32
    MSYS2: 1
  - TARGET: i686-pc-windows-msvc
    BITS: 32
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V
build: false
test_script:
  # TODO: Remove --no-default-features here. wabt and disass currently
  # don't build on appveyor due to cmake issues.
  - cargo build --verbose --all --no-default-features
  - cargo test --verbose --all --no-default-features
branches:
  only:
    - master
